# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "71bc1b7e50ef808886778d84485d2603"
name = "facturacion-app"
handle = "facturacion-app"
application_url = "https://ali-finance-interactive-lover.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "facturacion-b1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ali-finance-interactive-lover.trycloudflare.com/auth/callback",
  "https://ali-finance-interactive-lover.trycloudflare.com/auth/shopify/callback",
  "https://ali-finance-interactive-lover.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
